apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    service: graylog
  name: graylog
  namespace: graylog
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 9000
  - name: "514"
    port: 514
    targetPort: 514
  - name: "5555"
    port: 5555
    targetPort: 5555
  selector:
    service: graylog
status:
  loadBalancer: {}
