apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  name: graylog
  namespace: graylog
spec:
  replicas: 4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: graylog
    spec:
      containers:
      - env:
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: http://127.0.0.1:9000/
        - name: GRAYLOG_MESSAGE_JOURNAL_ENABLED
          value: "false"
        - name: GRAYLOG_PASSWORD_SECRET
          value: somepasswordpepper
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - name: GRAYLOG_SERVER_JAVA_OPTS
          value: -Xmx4G
        image: graylog/graylog:3.0
        name: graylog
        ports:
        - containerPort: 9000
        - containerPort: 514
        - containerPort: 5555
        resources:
          limits:
            memory: 1Gi
      restartPolicy: Always
status: {}
