apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    service: mongo
  name: mongo
  namespace: graylog
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongo
    spec:
      containers:
      - image: mongo:3
        name: mongo
        resources:
          limits:
            memory: 128Mi
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      restartPolicy: Always
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-persistent-storage
status: {}
